apiVersion: v1
kind: Secret
metadata:
  name: prod-ti-backend-secret
  namespace: prod
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL3Byb2RfdXNlcjE6NjVZS1Y1aFI1ZTZmQDEwLjEwLjE2LjIwOjMzMDYvbXlzcWw=
  SPRING_DATASOURCE_USERNAME: cHJvZF91c2VyMQ==
  SPRING_DATASOURCE_PASSWORD: NjVZS1Y1aFI1ZTZm
  SMS_KEY: VGFDYzhBUHI3N2ZXYndqUDdhRWtsUT09
  EMAIL_SMTP_USERNAME: YXBpa2V5
  EMAIL_SMTP_PASSWORD: U0cuc3BrQ2w2RzhRUGFmLUI3Y2lYczVGUS5HUmhMYUlERWxkeEhLbWQxYW5kbmVXeFNFTUZlSGR6c1JNRmR1RkpqUTlz
  EMAIL_SMTP_HOST: c210cC5zZW5kZ3JpZC5uZXQ=

