apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prod
  name: prod-ti-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-ti-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50